### ISSUE TITLE
Change app in main.py to absl.app

### ISSUE THREAD

**Issue by yx3110** [XHUJOY/pysc2-agents#4]
Following pysc2 commit f2f96c08c32ea92fa60485cc6d7307bc17c1c6db. The pysc2 repo does not contain app class anymore and it was replaced by Google's abseil (absl.app). 
Therefore the current version of main.py no longer works. For the conveniences of new users could you please update main.py by changing 
`from pysc2.lib import app` 
`import gflags as flags `
to
`from absl import app`
`from absl import flags`

**Comment by xiaowei-hu** [comment]
Thanks for your reminder.
